"""
watcher.py — Bronze Tier File System Watcher
Watches D:/bronze_tier/Inbox/ for new .md files and creates action items in D:/bronze_tier/Needs_Action/
Requires: pip install watchdog
"""

import os
import time
from datetime import datetime
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

# ── Folder paths ────────────────────────────────────────────────────────────
# Script lives in vault/ but Inbox & Needs_Action are one level up (D:\bronze_tier\)
BASE_DIR    = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INBOX_DIR   = os.path.join(BASE_DIR, "Inbox")
ACTION_DIR  = os.path.join(BASE_DIR, "Needs_Action")

# Make sure required folders exist
os.makedirs(INBOX_DIR,  exist_ok=True)
os.makedirs(ACTION_DIR, exist_ok=True)


def build_action_note(filename: str, content: str) -> str:
    """
    Build a structured Markdown action file from the inbox file's content.
    Returns the full text to write into Needs_Action/.
    """
    timestamp   = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    source_name = os.path.splitext(filename)[0]   # strip .md extension

    # Extract a one-line preview (first non-empty line of content)
    lines   = [ln.strip() for ln in content.splitlines() if ln.strip()]
    preview = lines[0] if lines else "(no content)"

    return f"""# Action Required — {source_name}

**Received:** {timestamp}
**Source file:** `Inbox/{filename}`

---

## Summary

> {preview}

---

## Full Content

{content.strip()}

---

## Next Steps

- [ ] Review the content above
- [ ] Decide: approve / delegate / discard
- [ ] Move this file to `Done/` when resolved

---
_Auto-generated by watcher.py_
"""


class InboxHandler(FileSystemEventHandler):
    """Handles file-system events inside the Inbox folder."""

    def on_created(self, event):
        # Ignore folder creation events; only care about files
        if event.is_directory:
            return

        filepath = event.src_path
        filename = os.path.basename(filepath)

        # Only process Markdown files
        if not filename.endswith(".md"):
            print(f"[SKIP]  Not a .md file: {filename}")
            return

        print(f"[NEW]   Detected: {filename}")

        # Small delay — give the OS time to finish writing the file
        time.sleep(0.5)

        # Read the inbox file
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                content = f.read()
        except Exception as e:
            print(f"[ERROR] Could not read {filename}: {e}")
            return

        # Build the action note content
        action_content = build_action_note(filename, content)

        # Write to Needs_Action/ with a timestamp prefix to avoid collisions
        timestamp_prefix = datetime.now().strftime("%Y%m%d_%H%M%S")
        out_filename = f"{timestamp_prefix}_{filename}"
        out_path     = os.path.join(ACTION_DIR, out_filename)

        try:
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(action_content)
            print(f"[DONE]  Action file created: Needs_Action/{out_filename}")
        except Exception as e:
            print(f"[ERROR] Could not write action file: {e}")


def main():
    print("=" * 50)
    print("  Bronze Tier Watcher — started")
    print(f"  Watching: {INBOX_DIR}")
    print(f"  Output:   {ACTION_DIR}")
    print("  Press Ctrl+C to stop.")
    print("=" * 50)

    event_handler = InboxHandler()
    observer      = Observer()

    # Register the handler to watch the Inbox folder (non-recursive)
    observer.schedule(event_handler, path=INBOX_DIR, recursive=False)
    observer.start()

    try:
        while True:
            time.sleep(1)   # keep the main thread alive
    except KeyboardInterrupt:
        print("\n[STOP]  Watcher stopped by user.")
        observer.stop()

    observer.join()


if __name__ == "__main__":
    main()
